version: '3.1'
services:
  db:
    image: postgres
    restart: always
    ports:
    - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: demo-service
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080